### ISSUE TITLE
 Create Flask App and Configure Isort, Black, Flake8, Pre-commit, Docker and more

### ISSUE THREAD

**Issue by NQTrung08** [NQTrung08/Chess-Server#1]
## User Story (Why) 📑

**Epic** này bao gồm các tác vụ thiết lập và cấu hình để tạo ứng dụng Flask cùng với việc thiết lập Isort, Black, Flake8 để tìm lỗi code, định cấu hình code để có kiểu dáng nhất quán và tích hợp pre-commit để chạy một số command trước khi commit.

Và còn nhiều thứ khác 👍 

## What should I do? 🤔

- Create Flask Application (https://blog.haposoft.com/structure-flask/)
- Configure Isort, Black, Flake8, Pre-commit (https://viblo.asia/p/format-code-python-tu-dong-su-dung-isort-black-flake8-va-pre-commit-3P0lPDEolox)
- Create Dockerfile

## What is the GOALs? 🤩

- **Efficient Flask Setup**: Bắt đầu một dự án Flask mới với cấu trúc được tổ chức tốt và có sẵn các tệp thiết yếu, giúp giảm thời gian và công sức thiết lập.
- **Code Quality Assurance**: Triển khai Flake8 với các quy tắc thích hợp để duy trì chất lượng mã nhất quán trong suốt dự án, giúp xác định và khắc phục sớm các vấn đề tiềm ẩn trong quá trình phát triển.
- ...

# Tasks

- [x] https://github.com/NQTrung08/Chess-Server/issues/2
- [x] https://github.com/NQTrung08/Chess-Server/issues/3
- [ ] https://github.com/NQTrung08/Chess-Server/issues/4
